---
title: "Assignment 7"
format: html
editor: visual
---

```{r}
library(tidyverse)

df <- data.frame(
  user = c("User 1", "User 2", "User 3", "User 4"),
  movie1 = c(5, 5, 1, 4),
  movie2 = c(1, NA, 4, 2),
  movie3 = c(4, 3, 2, NA),
  movie4 = c(NA, 2, 5, 1),
  movie5 = c(NA, 5, 2, 5),
  movie6 = c(NA, NA, NA, 2),
  movie7 = c(2, 2, 5, 3),
  movie8 = c(1, 1, 4, 3))

df1 <- data.frame(
x = c(5, 1, 4, NA, NA, NA, 2, 1),
y = c(5, NA, 3, 2, 5, NA, 2, 1),
z = c(1, 4, 2, 5, 2, NA, 5, 4),
t = c(4, 2, NA, 1, 5, 2, 3, 3))

df1
```

```{r}
r12 <- cor(df1$y, df1$x, use = "pairwise.complete.obs") # 0.962
r23 <- cor(df1$y, df1$z, use = "pairwise.complete.obs") # -0.832
r24 <- cor(df1$y, df1$t, use = "pairwise.complete.obs") # 0.721

# df1[6,2] = (r12/(r12 + r24))*(df1[6,1] - mean(df1$x, na.rm = T)) + (r24/(r12 + r24))*(df1[6,4] - mean(df1$t, na.rm = T))
# User 1 hasn't rated movie 6 so can't use this formula
df1[6,2] = round((r24/(r12 + r24))*(df1[6,4] - mean(df1$t, na.rm = T)) + mean(df1$y, na.rm = T))
df1[6,2]
```

```{r}
correlations <- sapply(
  df[2:9],
  function(x) cor(df$movie1, x, use = "complete.obs")
)

correlations

correlations_without_movie1 <- correlations[names(correlations) != "movie1"]
names(which.max(correlations_without_movie1)) # Outputs movie closest to movie 1
```

```{r}

countries <- read.csv("http://manctsui.github.io/datasets/countries.csv")

countries_imputed <- countries |>
  group_by(Region) |>
  mutate(Agriculture = if_else(is.na(Agriculture), mean(Agriculture, na.rm = TRUE), Agriculture),
    Industry = if_else(is.na(Industry), mean(Industry, na.rm = TRUE), Industry)) |>
  ungroup()

head(countries_imputed)
```

```{r}

countries |>
  group_by(Region) |>
  summarize(Total_NA = sum(is.na(Agriculture)) + sum(is.na(Industry))) |>
  ungroup()
```

```{r}

df <- data.frame(
temp = c(79, 74, 73, 76, 82, 72, 71, 79, 83, 70, 73, 75, 77),
chirps = c(44, 40, 38, 43, 48, 37, 34, 45, 51, 32, 35, 42, 43))

r <- cor(df$temp, df$chirps) # 0.97
mean_temp <- mean(df$temp) # 75.69
sd_temp <- sd(df$temp) # 4.11
mean_chirp <- mean(df$chirps) # 40.92
sd_chirp <- sd(df$chirps) # 5.59

# To get the line of best fit, temp = 0.714 * chirps + 46.474 
# 0.714 is the slope of the line, which would come for the correlation times the rise over the run, which is the sd of the temp over the sd of the chirps, or 0.97*(4.11)/(5.59) = 0.714
slope <- r*(sd_temp/sd_chirp)
# 46.474 is the 'y intercept' of the equation, which would be the amount of temp when there is 0 chirp, which can be calculated from mean temp - slope times mean chrips
y_intercept <- mean_temp - slope * mean_chirp

slope
y_intercept
```
